version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: rusunawa_db
    restart: always
    environment:
      POSTGRES_USER: rusun_user
      POSTGRES_PASSWORD: rusun_pass
      POSTGRES_DB: rusunawa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rusunawa_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rusun.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
