"""add_checkouts_and_fix_enums

Revision ID: 087ec09b18b5
Revises: 23bb0ba9c439
Create Date: 2026-04-10 09:45:45.582349

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087ec09b18b5'
down_revision: Union[str, None] = '23bb0ba9c439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Manual addition: fix rusunawasite enum labels ---
    op.execute("ALTER TYPE rusunawasite RENAME VALUE 'cigugur_tengah' TO 'Cigugur Tengah'")
    op.execute("ALTER TYPE rusunawasite RENAME VALUE 'cibeureum' TO 'Cibeureum'")
    # Note: 'leuwigajah' matches already if it's just case, but let's be safe
    op.execute("ALTER TYPE rusunawasite RENAME VALUE 'leuwigajah' TO 'Leuwigajah'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_sequences_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_system_sequences_year'), ['year'], unique=False)

    op.create_table('checkouts',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'cancelled', name='checkoutstatus'), nullable=False),
    sa.Column('inspection_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('final_refund_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('lampu', 'air', 'atap', 'lainnya', name='ticketcategory'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'progress', 'resolved', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('checkouts')
    with op.batch_alter_table('system_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_sequences_year'))
        batch_op.drop_index(batch_op.f('ix_system_sequences_key'))

    op.drop_table('system_sequences')
    # ### end Alembic commands ###

    # --- Manual addition: restore rusunawasite enum labels ---
    op.execute("ALTER TYPE rusunawasite RENAME VALUE 'Cigugur Tengah' TO 'cigugur_tengah'")
    op.execute("ALTER TYPE rusunawasite RENAME VALUE 'Cibeureum' TO 'cibeureum'")
    op.execute("ALTER TYPE rusunawasite RENAME VALUE 'Leuwigajah' TO 'leuwigajah'")
