"""add_pangkat_to_staff

Revision ID: 23bb0ba9c439
Revises: 7276ea330ff1
Create Date: 2026-04-08 18:30:25.779430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23bb0ba9c439'
down_revision: Union[str, None] = '7276ea330ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pangkat', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Data backfill for existing rows with NULL nik
    # Placeholder '0000000000000000' satisfies the 16-length constraint in model
    op.execute("UPDATE tenants SET nik = '0000000000000000' WHERE nik IS NULL")

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('nik',
               existing_type=sa.VARCHAR(),
               nullable=False)
        # Removed redundant create_index as it was already created in 7276ea330ff1

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        # Index ix_tenants_nik is managed by migration 7276ea330ff1
        batch_op.alter_column('nik',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('pangkat')

    # ### end Alembic commands ###
