"""Add sku_file_path to applications

Revision ID: 38ffab250ce1
Revises: ef34052e48b2
Create Date: 2026-04-04 13:19:04.632847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38ffab250ce1'
down_revision: Union[str, None] = 'ef34052e48b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('skck_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('health_cert_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('photo_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('has_signed_statement', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('has_signed_statement')
        batch_op.drop_column('photo_file_path')
        batch_op.drop_column('health_cert_file_path')
        batch_op.drop_column('skck_file_path')
        batch_op.drop_column('sku_file_path')

    # ### end Alembic commands ###
