"""add_nik_to_tenant

Revision ID: 7276ea330ff1
Revises: ef34052e48b2
Create Date: 2026-04-04 16:39:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7276ea330ff1'
down_revision: Union[str, None] = 'a03ed16ae80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('nik', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_tenants_nik'), 'tenants', ['nik'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_nik'), table_name='tenants')
    op.drop_column('tenants', 'nik')
    # ### end Alembic commands ###
