"""add_strd_fields

Revision ID: a03ed16ae80f
Revises: 38ffab250ce1
Create Date: 2026-04-04 20:45:32.687868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a03ed16ae80f'
down_revision: Union[str, None] = '38ffab250ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('strd_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoices', sa.Column('strd_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'strd_date')
    op.drop_column('invoices', 'strd_number')
    # ### end Alembic commands ###
