name: Deploy to DigitalOcean
on:
  push:
    branches:
      - master # Sesuaikan kalau branch utama kamu namanya 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /opt/rusunawa
            git pull origin master
            docker compose -f docker-compose.prod.yml build
            docker compose -f docker-compose.prod.yml up -d
